# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8383
        protocol: TCP
      - containerPort: 30090
        hostPort: 9393
        protocol: TCP
      - containerPort: 30081
        hostPort: 8181
        protocol: TCP
      - containerPort: 30082
        hostPort: 8282
        protocol: TCP