#  Copyright (c) 2025 Metaform Systems, Inc
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       Metaform Systems, Inc. - initial API and implementation
#

# Test REST client.
#
# Note that deployment manifests require a unique id. If the id is not unique, de-duplication will be performed and
# subsequent requests will be ignored. Requests therefore generate unique ids. In GoLand, this is done using {{$uuid}}.
# In VS Code, this is done with {{$guid}}. If you are executing requests using VS Code, you will need to change
# occurences of {{$uuid}} to {{$guid}}.

@cfmAgentBaseUrl = http://localhost:8383/
@pmanagerBaseUrl = http://localhost:8181/
@fulcrumCoreBaseUrl = http://localhost:8080/api/v1
@adminToken = admin-test-token


### createTestActivityDefinition
POST {{pmanagerBaseUrl}}/activity-definition

{
  "type": "test.activity",
  "description": "Performs a test activity"
}


### createTestDeploymentDefinition
POST {{pmanagerBaseUrl}}/deployment-definition

{
  "type": "test.deployment",
  "apiVersion": "v1",
  "resource": {
    "group": "deployments.example.com",
    "singular": "TestDeployment",
    "plural": "TestDeployments",
    "description": "Test deployment"
  },
  "versions": [
    {
      "version": "1.0.0",
      "active": true,
      "schema": {
        "openAPIV3Schema": {}
      },
      "activities": [
        {
          "id": "activity1",
          "type": "test-activity",
          "inputs": []
        }
      ]
    }
  ]
}


### createTestDeployment
POST {{pmanagerBaseUrl}}/deployment

{
  "DeploymentType": "test.deployment",
  "ID": "{{$uuid}}",
  "Payload": {}
}


### createServiceGroup
POST {{fulcrumCoreBaseUrl}}/service-groups
Authorization: Bearer {{adminToken}}

{
  "name": "cfm",
  "consumerID":"586a5fb8-86e1-4672-b490-b06d86f1b274"
}

### getServiceGroups
GET {{fulcrumCoreBaseUrl}}/service-groups
Authorization: Bearer {{adminToken}}

### getServiceTypes
GET {{fulcrumCoreBaseUrl}}/service-types
Authorization: Bearer {{adminToken}}

### getParticipants
GET {{fulcrumCoreBaseUrl}}/participants
Authorization: Bearer {{adminToken}}

### getAgents
GET {{fulcrumCoreBaseUrl}}/agents
Authorization: Bearer {{adminToken}}

### getJobs
GET {{fulcrumCoreBaseUrl}}/jobs
Authorization: Bearer {{adminToken}}

### getTokens
GET {{fulcrumCoreBaseUrl}}/tokens
Authorization: Bearer {{adminToken}}

